# Generated by Django 3.2.7 on 2022-05-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(help_text='Mersedes', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название машины',
            },
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_drive', models.CharField(help_text='Передний', max_length=255, verbose_name='Привод машины')),
            ],
            options={
                'verbose_name': 'Типы приводов',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuels', models.CharField(help_text='Бензин', max_length=100, verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Типы топлива',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transmission', models.CharField(max_length=255, verbose_name='Тип коробки передач')),
            ],
            options={
                'verbose_name': 'Типы коробок передач',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveBigIntegerField(default=0, help_text='120999', verbose_name='Пробег')),
                ('year', models.PositiveBigIntegerField(default=2000, help_text='2000', verbose_name='Год выпуска')),
                ('color', models.CharField(help_text='Черный', max_length=255, verbose_name='Цвет машины')),
                ('color_interior', models.CharField(help_text='Молочный', max_length=255, verbose_name='Цвет интерьера')),
                ('vin', models.CharField(help_text='JTJHY7AX6H42', max_length=255, verbose_name='VIN номер')),
                ('engine', models.CharField(help_text='V8 4.7', max_length=255, verbose_name='Двигатель')),
                ('brand', models.ForeignKey(help_text='Mersedes', on_delete=django.db.models.deletion.CASCADE, to='cars.brand', verbose_name='Название машины')),
                ('drive_type', models.ForeignKey(help_text='Передний', on_delete=django.db.models.deletion.CASCADE, to='cars.drivetype', verbose_name='Привод машины')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_fuel_type', to='cars.fuel', verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
