# Generated by Django 3.2.7 on 2022-05-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Название машины', 'verbose_name_plural': 'Название машины'},
        ),
        migrations.AlterModelOptions(
            name='drivetype',
            options={'verbose_name': 'Тип привода', 'verbose_name_plural': 'Типы приводов'},
        ),
        migrations.AlterModelOptions(
            name='fuel',
            options={'verbose_name': 'Тип топлива', 'verbose_name_plural': 'Типы топлива'},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={'verbose_name': 'Тип коробки передач', 'verbose_name_plural': 'Типы коробок передач'},
        ),
    ]
