# Generated by Django 3.2.7 on 2022-05-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default=1, upload_to='car_image/'),
            preserve_default=False,
        ),
    ]
