# Generated by Django 3.2.7 on 2022-05-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(upload_to='car_image/', verbose_name='Фотография автомобиля'),
        ),
    ]
