# Generated by Django 3.2.7 on 2022-05-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('cars', '0007_alter_car_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_category', to='categories.category', verbose_name='Тип машины'),
            preserve_default=False,
        ),
    ]
