# Generated by Django 3.2.7 on 2022-05-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='new_or_old',
            field=models.CharField(choices=[('Старый', 'Старый'), ('Новый', 'Новый')], default='Новый', max_length=255, verbose_name='Состояние машины'),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.PositiveBigIntegerField(default=1, help_text=1200000, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
