# Generated by Django 3.2.7 on 2022-05-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20220517_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
