# Generated by Django 3.2.7 on 2022-05-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_car_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ManyToManyField(help_text='Mersedes', to='cars.Brand', verbose_name='Название машины'),
        ),
    ]
