# Generated by Django 3.2.7 on 2022-05-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20220521_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default=1, help_text='Mersedes', on_delete=django.db.models.deletion.CASCADE, related_name='cars_brand', to='cars.brand', verbose_name='Название машины'),
            preserve_default=False,
        ),
    ]
